### ISSUE TITLE
 Host not found (non-authoritative)

### ISSUE THREAD

**Issue by czartm** [flopp999/NIBEUplink-Domoticz#30]
After a few minutes I received this message: Error: Plugin: Connection Exception: 'resolve: Host not found (non-authoritative), try again later' connecting to 'api.nibeuplink.com:443'

If I restarted domoticz it works for a while and again I received this message.

It's not a problem with network because after domoticz is restarted everything works fine.

**Comment by flopp999** [comment]
Hi, I also do get those errors. I have uploaded a new beta where I try to get rid of those errors, but still with new beta I get some errors, but maybe less error later than before

**Comment by flopp999** [comment]
@czartm are you still getting those errors?
