### ISSUE TITLE
NIBEUplink negative Unit number

### ISSUE THREAD

**Issue by hans-2022** [flopp999/NIBEUplink-Domoticz#39]
Hi, after getting the plugin working (had some of the same issues mentioned by Lundmatt), I am still stuck with 2 messages in the log. 

2022-03-01 16:37:20.435 Error: CPlugin:CDevice_init, illegal Unit number (-1), valid values range from 1 to 255.
2022-03-01 16:37:20.435 Error: Device refresh failed, Device object is not associated with a plugin. 

The -1 unit is in the devices list: 
![NIBE -1 unit](https://user-images.githubusercontent.com/100707094/156203265-5cb34c8f-2e87-4e7c-8220-7d23a685d820.JPG)

I can delete the -1 line from the domoticz devices list, but next time the plugin pulls data from NIBE it is back again. 

I have a 10 minute update interval. I get some 25 of these message in a 5 minute period and then 5 minutes no messages after which the sequence repeats. 

Not sure if this is bug or somehow user error.

**Comment by flopp999** [comment]
Hi, I need to rewrite the whole plugin to solve a function.

Today I have hard coded all parameters, but since there seems to be more parameters that I knew when I wrote the plugin, it can be that -1 Unit will be created

**Comment by hans-2022** [comment]
Hi flopp, 

Thanks for letting me know. No hurries here. For now I have what I need. While I am not much of a python programmer, I think I can assist with testing. Don't hesitate to get in touch should you want tests done.
